load_file_homepage:
    path:     /
    defaults: { _controller: AnalizPdvBundle:Default:index }

load_file_new:
    path: /new
    defaults: {_controller: AnalizPdvBundle:Default:new}
    methods:  [GET,POST]

view_all_load:
    path: /view
    defaults: {_controller: AnalizPdvBundle:Default:view}

load_file_newLoad:
    path: /new1
    defaults: {_controller: AnalizPdvBundle:Default:newLoad}
    methods:  [GET,POST]

LoadBranch:
    path: /LoadBranch
    defaults: {_controller: AnalizPdvBundle:LoadBranch:Load}

docErpn_search:
  path: /searchDocErpn
  defaults: {_controller: AnalizPdvBundle:searchDocErpn:viewForm}

# поиск всех документов ЕРПН и Реестрах в разрезе филиалов и (или) структурных подразделений
searchDocByBranch:
  path: /searchDocByBranch
  defaults: {_controller: AnalizPdvBundle:searchDoc:searchDocByBranch}

# поиск документов ЕРПН и Реестрах по параметрам
searchDocByParam:
  path: /searchDocByParam
  defaults: {_controller: AnalizPdvBundle:searchDoc:searchDocByParam}

analizInnOut:
  path: /analizInnOut
  defaults: {_controller: AnalizPdvBundle:analizDoc:analizInnOut}

getDoc_analizInnOut:
  path: /getDoc_analizInnOut/{month}/{year}/{numBranch}/{INN}/
  defaults: {_controller: AnalizPdvBundle:analizDoc:getDoc_analizInnOut}




