<?php

namespace AnalizPdvBundle\Entity\Repository;

/**
 * ErpnIn
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErpnIn extends \Doctrine\ORM\EntityRepository
{

}
