<?php

namespace AnalizPdvBundle\Entity\Repository;

/**
 * ReestrBranch_out
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReestrBranch_out extends \Doctrine\ORM\EntityRepository
{
}
