<?php

namespace LoadFileBundle\Entity\Repository;

/**
 * SprBranch
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprBranch extends \Doctrine\ORM\EntityRepository
{
    public function findCountBranch($NumBranch)
    {


    }
}
